--1번

SELECT STUDENT_NO AS 학번 , STUDENT_NAME AS 이름 , ENTRANCE_DATE AS 입학년도
FROM TB_STUDENT
WHERE DEPARTMENT_NO = '002'
ORDER BY 학번, 이름, 입학년도 ASC;

--2번
SELECT PROFESSOR_NAME, PROFESSOR_SSN
FROM TB_PROFESSOR
WHERE PROFESSOR_NAME LIKE '__'
OR PROFESSOR_NAME LIKE '____%';


--3번

SELECT PROFESSOR_NAME AS 교수이름 , FLOOR(MONTHS_BETWEEN(SYSDATE, TO_DATE('19' || 
SUBSTR(PROFESSOR_SSN, 1, 6), 'YYYYMMDD')) / 12 ) 나이
FROM TB_PROFESSOR
WHERE SUBSTR(PROFESSOR_SSN, 8, 1) = '1'
ORDER BY 나이 ASC;

--4번

SELECT SUBSTR(PROFESSOR_NAME, 2) AS 이름
FROM TB_PROFESSOR;

--5번

SELECT STUDENT_NO, STUDENT_NAME FROM TB_STUDENT
WHERE EXTRACT(YEAR FROM ENTRANCE_DATE) - LPAD(SUBSTR(STUDENT_SSN, 1, 2), 4, '19') >= 20;

--6번

SELECT TO_CHAR(TO_DATE('2020-12-25', 'YYYY-MM-DD'), 'DAY') AS 요일
FROM DUAL;

--7번

SELECT TO_CHAR(TO_DATE('99/10/11', 'YY/MM/DD')),
       TO_CHAR(TO_DATE('49/10/11', 'YY/MM/DD')),
       TO_CHAR(TO_DATE('99/10/11', 'RR/MM/DD')),
       TO_CHAR(TO_DATE('49/10/11', 'RR/MM/DD'))
FROM DUAL;


--8번

SELECT STUDENT_NO, STUDENT_NAME
FROM TB_STUDENT
WHERE SUBSTR(STUDENT_NO, 1, 1) != 'A';

--9번
SELECT ROUND(AVG(POINT), 1) AS 평점
FROM TB_GRADE
WHERE STUDENT_NO = 'A517178';

--10번
SELECT DEPARTMENT_NO AS "학과번호", COUNT(*) AS "학생수(명)"
FROM TB_STUDENT
GROUP BY DEPARTMENT_NO;


--11번
SELECT COUNT(*)
FROM TB_STUDENT
WHERE COACH_PROFESSOR_NO IS NULL;

--12번
SELECT SUBSTR(TERM_NO, 1, 4) AS 년도, ROUND(AVG(POINT), 1) AS "년도 별 평점"
FROM TB_GRADE
WHERE STUDENT_NO = 'A112113'
GROUP BY SUBSTR(TERM_NO, 1, 4)
ORDER BY 년도 ASC;


--13번
SELECT DEPARTMENT_NO AS 학과코드명, COUNT(*) AS "휴학생 수"
FROM TB_STUDENT
WHERE SUBSTR(ABSENCE_YN, 1) = 'Y'
GROUP BY DEPARTMENT_NO
ORDER BY 학과코드명 ASC;

--14번

SELECT STUDENT_NAME AS 동일이름, COUNT(*) AS "동명이인 수"
FROM TB_STUDENT
GROUP BY STUDENT_NAME
HAVING COUNT(*) > 1 
ORDER BY STUDENT_NAME ASC;




