--1번

CREATE TABLE TB_CATEGORY(
    NAME VARCHAR2(10),
    USE_YN CHAR(1) DEFAULT 'Y'
);

--2번

CREATE TABLE TB_CLASS_TYPE(
    NO VARCHAR2(5) PRIMARY KEY,
    NAME VARCHAR2(10)
);

--3번
ALTER TABLE TB_CATEGORY ADD PRIMARY KEY(NAME);

--4번
ALTER TABLE TB_CLASS_TYPE MODIFY NAME NOT NULL;

--5번
ALTER TABLE TB_CATEGORY MODIFY (NAME VARCHAR2(20));
ALTER TABLE TB_CLASS_TYPE MODIFY(NAME VARCHAR2(20), NO VARCHAR2(10));

--6번
ALTER TABLE TB_CLASS_TYPE RENAME COLUMN CATEGORY_NO TO CLASS_TYPE_NO;
ALTER TABLE TB_CATEGORY RENAME COLUMN NAME TO CATEGORY_NAME; 

--7번
ALTER TABLE TB_CLASS_TYPE DROP CONSTRAINT SYS_C008374;
ALTER TABLE TB_CATEGORY DROP CONSTRAINT SYS_C008375;
ALTER TABLE TB_CATEGORY ADD CONSTRAINT PK_CATEGORY_NAME PRIMARY KEY(CATEGORY_NAME);
ALTER TABLE TB_CLASS_TYPE ADD CONSTRAINT PK_CTYPE_NAME PRIMARY KEY(NAME);

--8번

ALTER TABLE TB_CATEGORY MODIFY CATEGORY_NAME VARCHAR2(30);
 
INSERT INTO TB_CATEGORY VALUES('공학', 'Y');
INSERT INTO TB_CATEGORY VALUES('자연과학', 'Y');
INSERT INTO TB_CATEGORY VALUES('의학', 'Y');
INSERT INTO TB_CATEGORY VALUES('예체능', 'Y');
INSERT INTO TB_CATEGORY VALUES('인문사회', 'Y');
COMMIT;

--9번
ALTER TABLE TB_DEPARTMENT ADD CONSTRAINT FK_DEPARTMENT_CATEGORY FOREIGN KEY(CATEGORY) 
REFERENCES TB_CATEGORY(CATEGORY_NAME);

--10번
CREATE OR REPLACE VIEW VW_학생일반정보 AS
SELECT STUDENT_NO,
STUDENT_NAME, 
STUDENT_ADDRESS
    FROM TB_STUDENT;
    
--11번

--12번
CREAT VIEW VW_학과별학생수 AS 
SELECT DEPARTMENT_NAME 학과이름,
       COUNT(STUDENT_NO) 학생수
       FROM TB_DEPARTMENT
       JOIN TB_STUDENT USING(DEPARTMENT_NO)
       GROUP BY DEPARTMENT_NAME;
       
--13번
UPDATE VW_학생일반정보
   SET STUDENT_NAME = '전진영'
 WHERE STUDENT_NO = 'A213046';

SELECT *
FROM VW_학생일반정보
WHERE STUDENT_NO = 'A213046';

--14번
    WITH READ ONLY를 마지막에 추가
    
--15번
